### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by nono2chan** [nono2chan/protospace-39100#1]
# URL
http://localhost:3000/

**Comment by motomuun** [comment]
@nono2chan さん、ご提出ありがとうございます‼︎

今回お送りいただいたURLはローカル環境のURLでございます。
本番環境のURLを再度コメントに添えて頂き、以下のprotospace完了報告フォームのご提出お願いします！

※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by nono2chan** [comment]
https://protospace-39100-jyae.onrender.com
実装課題の提出となります。
ご確認お願いいたします。

**Comment by shodai-ito** [comment]
@nono2chan さん、本番環境のURL添付ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **プロフィール・所属・役職が必須であること**
上記の３項目が空欄でもユーザー登録ができてしまいます。

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
一部表示が「ユーザー名」のままになっております。
該当ユーザーの名前が表示されるように編集しましょう。
<img width="851" alt="スクリーンショット 2023-07-08 17 20 55" src="https://github.com/nono2chan/protospace-39100/assets/62537107/f92557da-6bea-4f7a-8b89-94cdf4e7336e">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by nono2chan** [comment]
ご確認いただきありがとうございます。
修正いたしましたので、再提出いたします。

**Comment by shodai-ito** [comment]
@nono2chan さん、再度ご提出いただきありがとうございます‼︎
動作の確認をしたところ、前回の指摘点について修正が確認できませんでした。
マージやデプロイ忘れの可能性もございます。
引き続き、上記内容のご確認をお願い致します！

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by nono2chan** [comment]
マージデプロイのし忘れでした。。。
動作確認をしまして、再提出をしておりますのでご確認お願いいたします！

**Comment by shodai-ito** [comment]
@nono2chan さん、デプロイありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
